<center><b>©  Content is made available under the CC-BY-NC-ND 4.0 license. Christian Lopez, lopezbec@lafayette.edu<center>

![alt text](https://miro.medium.com/max/1200/1*Xp5sVXs0C7na22Jb5lKw3Q.png)



#Introduction to Python's NumPy library
 This notebooks and the exercise on it will give you a brief introduction to Python's [NumPy](https://https://numpy.org/) library. 
<br>

Most of the notebooks we are going to be using are inspired from existing notebooks that available online and are made  free for educational purposes (e.g., the work of [Andre Ng]( https://en.wikipedia.org/wiki/Andrew_Ng) and the notebooks from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do)). Nonetheless, the notebooks should not be share without prior permission of the instructor. When working in an assignment always remember the [Student Code of Conduct]( https://conduct.lafayette.edu/student-handbook/student-code-of-conduct/).  



# NumPy Basics with Google Colab 

This assigment will gives you a brief introduction to Python's [NumPy](https://https://numpy.org/) library. Even if you've used Python's NumPy before, this will help familiarize you with functions you'll need.  

<br><br>
**After this assignment you will:**
- Use and undestand NumPy arrays



###**Instructions:**
- You will be using Python 3.

- Only modify the code that is within the comments:

`### START CODE HERE ###`

`### END CODE HERE ###`

- You need to run all the code cells on the notebok sequentially
- If you are asked to change/update a cell, change/update and run it to check if your result is correct.


*The following sections were inspired and uses code and text from the  [Introduction to NumPy Notebook](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.00-Introduction-to-NumPy.ipynb#scrollTo=4CLEDpyacmUk) from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do)[](https://jupyter.brynmawr.edu/hub/login) 

##1- Introduction to NumPy

This Notebooks will cover Python's NumPy (NumPy=*Numerical Python*). This library  provides an efficient interface to store and operate on dense data buffers.

In some ways, NumPy arrays are like Python's built-in ``list`` type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size. Hence, learning to use NumPy effectively will be valuable for you when developmenting and implementing Machine Learning algorithms.

Google Colab has Numpy already installed in the VM environment, you just need to import it.

In [72]:
import numpy
numpy.__version__

'1.19.5'

By convention, you'll find that most people  will import NumPy using ``np`` as an alias:

In [73]:
import numpy as np

**Reminder about  Built In Documentation**

As you read through this chapter, don't forget that Jupyter Notebooks gives you the ability to quickly explore the contents of a package (by using the tab-completion feature), as well as the documentation of various functions (using the ``?`` character – Refer back to "Python_Basics" Notebook.



For example, to display all the contents of the NumPy namespace, you can type this:


```ipythoseveralseseefefe
np.
```

And to display NumPy's built-in documentation, you can use this:

```ipython
np?
```

Now, you go ahead and try it:

##2- NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like [Pandas](https://pandas.pydata.org/) are built around the NumPy array.

This Nothebook will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.

While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks for making several of the Machine Learning algorithms, covered in this course, more efficient by using vectors and matrices.

We'll cover a few categories of basic array manipulations here.

### 2.1- Creating NumPy Arrays

**Make an array from a list.**


In [74]:
list1=[1,2,4]
list2=[3,5,6]

In [75]:
list1_array=np.array(list1)
list12_array=np.array([list1,list2])

In [76]:
print(list1_array)

[1 2 4]


Pay attention to the `[ ]` in the list12_array. This means that you can think of `list12_array` as a list of a list!

You can display these arrays by using the `print()` function:

In [77]:
print(list12_array)

[[1 2 4]
 [3 5 6]]


**Make an array using a function**

The arrays made in previous code cells were based on us supplying the list or values.

Very often we need large arrays and it is not possible to use our current approach and thus we need to use array creating functions. The most important functions are `zeros` and `ones`. They both take a parameter called shape which determines the shape of the output array.
* `zeros` makes an array which is all 0 [see documentation here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)
* `ones`  makes an array which is all 1 [see documentation here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones)

In [78]:
np.zeros(shape=(2, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

####**Exercise:**


Now create an 2-dimentional array of ones of shape (4,4), and store it in `np441

In [79]:
np441=0
### START CODE HERE ### (≈ 1 line of code)

### END CODE HERE ###

In [80]:
try:
    print("np441=")
    print(np441)
    print("Shape="+ str(np441.shape))
except Exception as e:
    print("Something is not working right")
    print(e)

np441=
0
Something is not working right
'int' object has no attribute 'shape'


Expected output: 
```
np441=
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape=(4, 4)
```


Another function we will use is`arange`, which is the exact same thing as regular python `range` except giving back a numpy array.

This functions requires only a single argument which is the end point. The start point is assumed to be 0 and step is assumed to be 1. In this variety when in takes three parameters, the first one is the start, second one is the end and the third one is the step.


####**Exercise:**

 Now make an array of four evenly spaced odd numbers starting from 1, and store it in `npodds`

In [81]:
npodds=0
### START CODE HERE ### (≈ 1 line of code)

### END CODE HERE ###


In [82]:
try:
    print("npodds=")
    print(npodds)
    print("Shape="+ str(npodds.shape))
except Exception as e:
    print("Something is not working right")
    print(e)

npodds=
0
Something is not working right
'int' object has no attribute 'shape'


Expected output: 
```
npodds=
[1 3 5 7]
Shape=(4,)
```


 NumPy's also has a random number generator `np.random.`, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run. This is critical for reproducibility when training and testing ML models.

Before we create the arrays with random values, lets look at the `np.random` module. 

Display NumPy's built-in documentation for the `np.random`, `np.random.normal` and `np.random.randint`



Now we can create a one-dimensional and two-dimensional arrays with:

In [83]:
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3,5))  # Two-dimensional array

In [84]:
print(x1)

[5 0 3 3 7 9]


In [85]:
print(x2)

[[3 5 2 4 7]
 [6 8 8 1 6]
 [7 7 8 1 5]]


### 2.2- NumPy Array Attributes

Let's discuss some useful array attributes. Each array has the attributes:``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array).

In [86]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape: (3, 5)
x2 size:  15


- We have `x2 ndim: 2` since this is a two-dimensional array.

- We have `x2 shape: (3,5)` since this is a two-dimensional array with 3 rows and 5 columns.

- We have `x2 size: 15` since this is a two-dimensional array with 15 elements. 

Another useful attribute is the ``dtype``, the data type of the array:

In [87]:
print("dtype:", x2.dtype)

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [88]:
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 120 bytes


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

####**Exercise**:

 Now store the (i) dimension, (ii) shape, (iii)size and (iv) the total size in bytes of the array x1 in: (remove the 0s for your code)



In [89]:
### START CODE HERE ### (= 4 line of code)
x1dim=   0                    #Store the dimension of array x1
x1shape= 0                #Store the shape of array x1
x1size=  0                 #Store the size of array x1
x1sizeb= 0                 #Store the size in bytes of array x1
### END CODE HERE ###

In [90]:
try:
    print("x1 dimensions: ", x1dim)
    print("x1 shape:", x1shape)
    print("x1 size: ", x1size)
    print("x1 size [bytes]:", x1sizeb)
except Exception as e:
    print("Something is not working right")
    print(e)

x1 dimensions:  0
x1 shape: 0
x1 size:  0
x1 size [bytes]: 0


Expected output: 
```
x1 dimmentions:  1
x1 shape: (6,)
x1 size:  6
x1 size [bytes]: 48
```

Some of the output is as we should have expected. The dimention of x1 is `1`, its size is `6`, and the size in bytes is `48` (6x8=48). However, what about the shape...`(6,)`?

This can be interpreted as x1 being a vector. However, this is a vector for indexing purposes, it is not column nor a row vector. 

To make a colums or a row vector you will need to use reshape (covered bellow ) or:

In [91]:
np.random.seed(0)  # seed for reproducibility
row_vectx1 = np.random.randint(10, size=(1,6))  # Row vector (2-dimensional array)
print(row_vectx1)
print("x1 shape:",row_vectx1.shape)

[[5 0 3 3 7 9]]
x1 shape: (1, 6)


In [92]:
np.random.seed(0)  # seed for reproducibility
col_vectx1 = np.random.randint(10, size=(6,1))  # Colums vector (2-dimensional array)
print(col_vectx1)
print("x1 shape:", col_vectx1.shape)


[[5]
 [0]
 [3]
 [3]
 [7]
 [9]]
x1 shape: (6, 1)


####**Exercise**

 Create a 3-dimensional array with shape= (3,4,2) and fill with numbers draw from a normal distribution with mean=5, and Standard Deviation=1



In [93]:
np.random.seed(0)  # seed for reproducibility
x3D_normal=0
### START CODE HERE ### (≈ 1 line of code)
                    # Row vector (2-dimensional array)
### END CODE HERE ###

In [94]:
try:
    print("x3D_normal=")
    print(x3D_normal)
    print("Shape="+ str(x3D_normal.shape))
except Exception as e:
    print("Something is not working right")
    print(e)

x3D_normal=
0
Something is not working right
'int' object has no attribute 'shape'


Expected output: 
```
x3D_normal=
[[[6.76405235 5.40015721]
  [5.97873798 7.2408932 ]
  [6.86755799 4.02272212]
  [5.95008842 4.84864279]]

 [[4.89678115 5.4105985 ]
  [5.14404357 6.45427351]
  [5.76103773 5.12167502]
  [5.44386323 5.33367433]]

 [[6.49407907 4.79484174]
  [5.3130677  4.14590426]
  [2.44701018 5.6536186 ]
  [5.8644362  4.25783498]]]
Shape=(3, 4, 2)
```

##3- Indexing Array

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In Python, as is in many other programming languages all arrays start from 0 so the first element is at position 0.

In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists, like:


In [95]:
x1[0]

5

In [96]:
x1[4]

7

To index from the end of the array, you can use negative indices.To access the last element we can use -1 as the index. `x[-1]` is identical to `x[x.shape[0] - 1]` where `shape[0]` is the length or rows of the array.

In [97]:
x1[-1]

9

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [98]:
x2[0, 0]

3

In [99]:
x2[2, -1]

5

Values can also be modified using any of the above index notation:

In [100]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4,  7],
       [ 6,  8,  8,  1,  6],
       [ 7,  7,  8,  1,  5]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [101]:
x1.dtype

dtype('int64')

In [102]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## 4- Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### 4.1- One-dimensional subarrays

In [103]:
x1

array([3, 0, 3, 3, 7, 9])

In [104]:
x1[:]  # all elements

array([3, 0, 3, 3, 7, 9])

In [105]:
x1[:5]  # first five elements

array([3, 0, 3, 3, 7])

In [106]:
x1[5:]  # elements after index 5

array([9])

In [107]:
x1[4:7]  # middle sub-array

array([7, 9])

In [108]:
x1[::2]  # every other element

array([3, 3, 7])

In [109]:
x1[1::2]  # every other element, starting at index 1

array([0, 3, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [110]:
x1[::-1]  # all elements, reversed

array([9, 7, 3, 3, 0, 3])

In [111]:
x1[5::-2]  # reversed every other from index 5

array([9, 3, 0])

### 4.2- Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [112]:
x2

array([[12,  5,  2,  4,  7],
       [ 6,  8,  8,  1,  6],
       [ 7,  7,  8,  1,  5]])

In [113]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 6,  8,  8]])

In [114]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2,  7],
       [ 6,  8,  6],
       [ 7,  8,  5]])

Finally, subarray dimensions can even be reversed together:

In [115]:
x2[::-1, ::-1]

array([[ 5,  1,  8,  7,  7],
       [ 6,  1,  8,  8,  6],
       [ 7,  4,  2,  5, 12]])

####4.2.1- Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [116]:
print(x2[:, 0])  # first column of x2

[12  6  7]


In [117]:
print(x2[0, :])  # first row of x2

[12  5  2  4  7]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [118]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4  7]


###4.3- Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [119]:
print(x2)

[[12  5  2  4  7]
 [ 6  8  8  1  6]
 [ 7  7  8  1  5]]


Let's extract a $2 \times 2$ subarray from this:

In [120]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 6  8]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [121]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 6  8]]


In [122]:
print(x2)

[[99  5  2  4  7]
 [ 6  8  8  1  6]
 [ 7  7  8  1  5]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

###4.4-Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [123]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 6  8]]


If we now modify this subarray, the original array is not touched:

In [124]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 6  8]]


In [125]:
print(x2)

[[99  5  2  4  7]
 [ 6  8  8  1  6]
 [ 7  7  8  1  5]]


##5- Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [126]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size (number of elements) of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [127]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [128]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [129]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [130]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

##6- Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

###6.1- Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [131]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [132]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [133]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [134]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [135]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [136]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [137]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Similary, ``np.dstack`` will stack arrays along the third axis.

###6.2- Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [138]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [139]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [140]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [141]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, ``np.dsplit`` will split arrays along the third axis.

#More about NumPy !!!



More detailed documentation, along with tutorials and other resources, can be found at http://www.numpy.org. 

In addition, I will encourage  you to go over the Notebooks from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) that cover NumPy:


- [Computation on NumPy Arrays: Universal Functions](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.03-Computation-on-arrays-ufuncs.ipynb#scrollTo=Vwsyz5AZ-UCs)

- [Aggregations: Min, Max, and Everything In Between](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.04-Computation-on-arrays-aggregates.ipynb)

- [Computation on Arrays: Broadcasting](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.05-Computation-on-arrays-broadcasting.ipynb#scrollTo=dnDVbi-C-riP)

- [Comparisons, Masks, and Boolean Logic](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.06-Boolean-Arrays-and-Masks.ipynb#scrollTo=LuPLpJi1--Ka)

- [Fancy Indexing](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.07-Fancy-Indexing.ipynb)

- [Sorting Arrays](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.08-Sorting.ipynb)

- [Structured Data: NumPy's Structured Arrays](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.09-Structured-Data-NumPy.ipynb)

## **DO NOT DELETE NOR MODIFY THESE CODE CELLS**

In [142]:
# ###DO NOT DELETE NOR MODIFY THIS CODE CELL####
# ###DO NOT DELETE NOR MODIFY THIS CODE CELL####
!wget https://raw.githubusercontent.com/lopezbec/intro_python_notebooks/main/Grading_Numpy.py

import numpy as np

from Grading_Numpy import GRADING_NumPy_intro

try:
    np441
except NameError:
    np441 = None
try:
    npodds
except NameError:
    npodds = None
try:
    x1dim
except NameError:
    x1dim = None
try:
    x1shape
except NameError:
    x1shape = None
try:
    x1size
except NameError:
    x1size = None
try:
    x1sizeb
except NameError:
    x1sizeb = None
try:
    x3D_normal
except NameError:
    x3D_normal = None



GRADING_NumPy_intro(np441,npodds,x1dim,x1shape,x1size,x1sizeb,x3D_normal)

--2022-02-09 19:32:46--  https://raw.githubusercontent.com/lopezbec/intro_python_notebooks/main/Grading_Numpy.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2391 (2.3K) [text/plain]
Saving to: ‘Grading_Numpy.py.1’

Grading_Numpy.py.1  100%[===================>]   2.33K  --.-KB/s    in 0s      

2022-02-09 19:32:46 (36.7 MB/s) - ‘Grading_Numpy.py.1’ saved [2391/2391]

np441 : False
npodds : False
x1dim : False
x1shape : False
x1size : False
x1sizeb : False
x3D_normal : False
